\documentclass{article}
\usepackage[utf8]{inputenc}


\title{Introdução ao \textit{tidyverse}}
\author{Igo da Costa Andrade}
\date{}

\begin{document}

\maketitle

<<include=FALSE>>=
library(gapminder)
library(dplyr)
@

\section{O \textit{dataset} gapminder}

Visão geral dos dados:
<<>>=
gapminder
@

\subsection{Filtragem de dados}
<<>>=
gapminder %>%
    filter(year==2007)

@


    
\end{document}